{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "dc0493e6",
   "metadata": {},
   "source": [
    "# L1 spectrum value check\n",
    "\n",
    "> Check that all L1 spectra have valid flux/ivar/sensfunc arrays."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "23332175-f8be-4b76-927d-438042c90a2d",
   "metadata": {},
   "outputs": [],
   "source": [
    "# |default_exp diagnostics.l1_spectrum_value_check"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "19db9eab",
   "metadata": {},
   "outputs": [],
   "source": [
    "# |export\n",
    "\n",
    "import matplotlib.pyplot as plt\n",
    "import numpy as np\n",
    "\n",
    "from qagmire.data import (\n",
    "    get_lr_l1_single_files,\n",
    "    read_l1_data,\n",
    ")\n",
    "from qagmire.quality_assurance import Diagnostics"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "727cd5c3-93ed-47b2-bc6f-5407ace40e3a",
   "metadata": {},
   "source": [
    "To write checks of the data, we create a subclass of `Diagnostics` and implement the `tests` method."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "14c43461-0a77-4ca8-8beb-571511201134",
   "metadata": {},
   "outputs": [],
   "source": [
    "# |export\n",
    "\n",
    "\n",
    "class L1SpectrumValueCheck(Diagnostics):\n",
    "    \"\"\"L1 spectrum value check.\n",
    "\n",
    "    A reproduction of the class with the same name in the weaveio\n",
    "    [value_checks](https://github.com/bamford/QAG/blob/master/diagnostics/value_checks.py).\n",
    "\n",
    "    This tests for the following cases:\n",
    "\n",
    "    * Are there non-finite pixel values?\n",
    "\n",
    "    for the red and blue 'flux', 'flux_noss', 'ivar', 'ivar_noss' and 'sensfunc' arrays, as well as:\n",
    "\n",
    "    * Are there negative pixel values?\n",
    "\n",
    "    for the red and blue 'ivar', 'ivar_noss' and 'sensfunc' arrays.\n",
    "    \"\"\"\n",
    "\n",
    "    def __init__(\n",
    "        self,\n",
    "        n_allowed_bad: int = 0,  # the number of allowed bad pixels per spectrum\n",
    "        camera=None,  # limit to a specific camera: RED or BLUE\n",
    "    ):\n",
    "        self.n_allowed_bad = n_allowed_bad\n",
    "        self.camera = camera.upper()\n",
    "        super().__init__()\n",
    "\n",
    "    def tests(self, **kwargs):\n",
    "        files = get_lr_l1_single_files(**kwargs)\n",
    "        data = read_l1_data(files)\n",
    "\n",
    "        if self.camera is not None:\n",
    "            camera_match = data[\"CAMERA\"] == self.camera\n",
    "            data = data.sel(filename=camera_match)\n",
    "            cameras = [self.camera]\n",
    "        else:\n",
    "            cameras = [\"RED\", \"BLUE\"]\n",
    "\n",
    "        # perform the tests by RUN, rather than filename\n",
    "        data = data.swap_dims(filename=\"RUN\")\n",
    "\n",
    "        neg = data < 0\n",
    "        nan = ~np.isfinite(data)\n",
    "\n",
    "        any_neg = neg.any(dim=[\"LAMBDA_R\", \"LAMBDA_B\"])\n",
    "        any_nan = nan.any(dim=[\"LAMBDA_R\", \"LAMBDA_B\"])\n",
    "\n",
    "        tests = []\n",
    "        for camera in cameras:\n",
    "            camera_match = data[\"CAMERA\"] == camera\n",
    "            for ext in [\"FLUX\", \"FLUX_NOSS\", \"IVAR\", \"IVAR_NOSS\", \"SENSFUNC\"]:\n",
    "                name = f\"{camera}_{ext}\"\n",
    "                tests.append(\n",
    "                    {\n",
    "                        \"name\": f\"nans_in_{name}\",\n",
    "                        \"description\": f\"Are there non-finite values in {name}?\",\n",
    "                        \"test\": any_nan[name] & camera_match,\n",
    "                    }\n",
    "                )\n",
    "            for ext in [\"IVAR\", \"IVAR_NOSS\", \"SENSFUNC\"]:\n",
    "                name = f\"{camera}_{ext}\"\n",
    "                tests.append(\n",
    "                    {\n",
    "                        \"name\": f\"negs_in_{name}\",\n",
    "                        \"description\": f\"Are there negative values in {name}?\",\n",
    "                        \"test\": any_neg[name] & camera_match,\n",
    "                    }\n",
    "                )\n",
    "        return tests"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "2a869a09-e290-476e-9dbc-fdbca7b11df3",
   "metadata": {},
   "source": [
    "## Tests"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "7b930acc-a370-4e59-ad35-a069483da7c1",
   "metadata": {},
   "source": [
    "We use multiple `dask` workers to speed up this test."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "54b86683-d4f0-4fc4-85e2-2548c3d647f7",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/home2/bamford/anaconda/envs/qagmire/lib/python3.12/contextlib.py:144: UserWarning: Creating scratch directories is taking a surprisingly long time. (4.07s) This is often due to running workers on a network file system. Consider specifying a local-directory to point workers to write scratch data to a local disk.\n",
      "  next(self.gen)\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-9774' coro=<Client._gather.<locals>.wait() done, defined at /home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py:2208> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py\", line 2217, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-9764' coro=<Client._gather.<locals>.wait() done, defined at /home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py:2208> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py\", line 2217, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-9765' coro=<Client._gather.<locals>.wait() done, defined at /home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py:2208> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py\", line 2217, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-9766' coro=<Client._gather.<locals>.wait() done, defined at /home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py:2208> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py\", line 2217, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-9767' coro=<Client._gather.<locals>.wait() done, defined at /home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py:2208> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py\", line 2217, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-9768' coro=<Client._gather.<locals>.wait() done, defined at /home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py:2208> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py\", line 2217, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-9756' coro=<Client._gather.<locals>.wait() done, defined at /home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py:2208> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py\", line 2217, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-9758' coro=<Client._gather.<locals>.wait() done, defined at /home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py:2208> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py\", line 2217, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-9759' coro=<Client._gather.<locals>.wait() done, defined at /home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py:2208> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py\", line 2217, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-9763' coro=<Client._gather.<locals>.wait() done, defined at /home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py:2208> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py\", line 2217, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-9740' coro=<Client._gather.<locals>.wait() done, defined at /home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py:2208> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py\", line 2217, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-9748' coro=<Client._gather.<locals>.wait() done, defined at /home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py:2208> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py\", line 2217, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-9749' coro=<Client._gather.<locals>.wait() done, defined at /home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py:2208> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py\", line 2217, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-9750' coro=<Client._gather.<locals>.wait() done, defined at /home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py:2208> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py\", line 2217, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-9751' coro=<Client._gather.<locals>.wait() done, defined at /home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py:2208> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py\", line 2217, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-9752' coro=<Client._gather.<locals>.wait() done, defined at /home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py:2208> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py\", line 2217, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-9753' coro=<Client._gather.<locals>.wait() done, defined at /home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py:2208> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py\", line 2217, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-9741' coro=<Client._gather.<locals>.wait() done, defined at /home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py:2208> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py\", line 2217, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-9742' coro=<Client._gather.<locals>.wait() done, defined at /home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py:2208> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py\", line 2217, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-9743' coro=<Client._gather.<locals>.wait() done, defined at /home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py:2208> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py\", line 2217, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-9747' coro=<Client._gather.<locals>.wait() done, defined at /home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py:2208> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py\", line 2217, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-9832' coro=<Client._gather.<locals>.wait() done, defined at /home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py:2208> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py\", line 2217, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-9876' coro=<Client._gather.<locals>.wait() done, defined at /home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py:2208> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py\", line 2217, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-9775' coro=<Client._gather.<locals>.wait() done, defined at /home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py:2208> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py\", line 2217, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-9771' coro=<Client._gather.<locals>.wait() done, defined at /home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py:2208> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py\", line 2217, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-9754' coro=<Client._gather.<locals>.wait() done, defined at /home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py:2208> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py\", line 2217, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-9853' coro=<Client._gather.<locals>.wait() done, defined at /home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py:2208> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py\", line 2217, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-9838' coro=<Client._gather.<locals>.wait() done, defined at /home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py:2208> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py\", line 2217, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-9895' coro=<Client._gather.<locals>.wait() done, defined at /home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py:2208> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py\", line 2217, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-9896' coro=<Client._gather.<locals>.wait() done, defined at /home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py:2208> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py\", line 2217, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-9897' coro=<Client._gather.<locals>.wait() done, defined at /home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py:2208> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py\", line 2217, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-9898' coro=<Client._gather.<locals>.wait() done, defined at /home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py:2208> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py\", line 2217, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-9900' coro=<Client._gather.<locals>.wait() done, defined at /home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py:2208> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py\", line 2217, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-9892' coro=<Client._gather.<locals>.wait() done, defined at /home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py:2208> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py\", line 2217, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-9879' coro=<Client._gather.<locals>.wait() done, defined at /home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py:2208> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py\", line 2217, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-9878' coro=<Client._gather.<locals>.wait() done, defined at /home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py:2208> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py\", line 2217, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-9886' coro=<Client._gather.<locals>.wait() done, defined at /home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py:2208> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py\", line 2217, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-9891' coro=<Client._gather.<locals>.wait() done, defined at /home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py:2208> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py\", line 2217, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-9795' coro=<Client._gather.<locals>.wait() done, defined at /home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py:2208> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py\", line 2217, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-9797' coro=<Client._gather.<locals>.wait() done, defined at /home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py:2208> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py\", line 2217, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-9800' coro=<Client._gather.<locals>.wait() done, defined at /home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py:2208> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py\", line 2217, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-9789' coro=<Client._gather.<locals>.wait() done, defined at /home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py:2208> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py\", line 2217, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-9790' coro=<Client._gather.<locals>.wait() done, defined at /home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py:2208> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py\", line 2217, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-9791' coro=<Client._gather.<locals>.wait() done, defined at /home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py:2208> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py\", line 2217, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-9792' coro=<Client._gather.<locals>.wait() done, defined at /home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py:2208> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py\", line 2217, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-9846' coro=<Client._gather.<locals>.wait() done, defined at /home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py:2208> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py\", line 2217, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-9847' coro=<Client._gather.<locals>.wait() done, defined at /home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py:2208> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py\", line 2217, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-9848' coro=<Client._gather.<locals>.wait() done, defined at /home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py:2208> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py\", line 2217, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-9849' coro=<Client._gather.<locals>.wait() done, defined at /home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py:2208> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py\", line 2217, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-9850' coro=<Client._gather.<locals>.wait() done, defined at /home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py:2208> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py\", line 2217, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-9851' coro=<Client._gather.<locals>.wait() done, defined at /home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py:2208> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py\", line 2217, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-9840' coro=<Client._gather.<locals>.wait() done, defined at /home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py:2208> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py\", line 2217, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-9841' coro=<Client._gather.<locals>.wait() done, defined at /home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py:2208> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py\", line 2217, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-9843' coro=<Client._gather.<locals>.wait() done, defined at /home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py:2208> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py\", line 2217, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-9844' coro=<Client._gather.<locals>.wait() done, defined at /home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py:2208> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py\", line 2217, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-9845' coro=<Client._gather.<locals>.wait() done, defined at /home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py:2208> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py\", line 2217, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-9887' coro=<Client._gather.<locals>.wait() done, defined at /home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py:2208> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py\", line 2217, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-9890' coro=<Client._gather.<locals>.wait() done, defined at /home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py:2208> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py\", line 2217, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-9888' coro=<Client._gather.<locals>.wait() done, defined at /home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py:2208> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py\", line 2217, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-9830' coro=<Client._gather.<locals>.wait() done, defined at /home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py:2208> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py\", line 2217, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-9833' coro=<Client._gather.<locals>.wait() done, defined at /home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py:2208> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py\", line 2217, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-9834' coro=<Client._gather.<locals>.wait() done, defined at /home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py:2208> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py\", line 2217, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-9836' coro=<Client._gather.<locals>.wait() done, defined at /home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py:2208> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py\", line 2217, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-9824' coro=<Client._gather.<locals>.wait() done, defined at /home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py:2208> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py\", line 2217, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-9827' coro=<Client._gather.<locals>.wait() done, defined at /home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py:2208> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py\", line 2217, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-9828' coro=<Client._gather.<locals>.wait() done, defined at /home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py:2208> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py\", line 2217, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-9829' coro=<Client._gather.<locals>.wait() done, defined at /home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py:2208> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py\", line 2217, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-9884' coro=<Client._gather.<locals>.wait() done, defined at /home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py:2208> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py\", line 2217, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-9818' coro=<Client._gather.<locals>.wait() done, defined at /home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py:2208> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py\", line 2217, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-9819' coro=<Client._gather.<locals>.wait() done, defined at /home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py:2208> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py\", line 2217, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-9820' coro=<Client._gather.<locals>.wait() done, defined at /home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py:2208> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py\", line 2217, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-9821' coro=<Client._gather.<locals>.wait() done, defined at /home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py:2208> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py\", line 2217, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-9822' coro=<Client._gather.<locals>.wait() done, defined at /home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py:2208> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py\", line 2217, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-9823' coro=<Client._gather.<locals>.wait() done, defined at /home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py:2208> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py\", line 2217, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-9812' coro=<Client._gather.<locals>.wait() done, defined at /home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py:2208> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py\", line 2217, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-9813' coro=<Client._gather.<locals>.wait() done, defined at /home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py:2208> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py\", line 2217, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-9814' coro=<Client._gather.<locals>.wait() done, defined at /home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py:2208> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py\", line 2217, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-9815' coro=<Client._gather.<locals>.wait() done, defined at /home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py:2208> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py\", line 2217, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-9817' coro=<Client._gather.<locals>.wait() done, defined at /home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py:2208> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py\", line 2217, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-9881' coro=<Client._gather.<locals>.wait() done, defined at /home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py:2208> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py\", line 2217, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-9805' coro=<Client._gather.<locals>.wait() done, defined at /home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py:2208> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py\", line 2217, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-9806' coro=<Client._gather.<locals>.wait() done, defined at /home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py:2208> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py\", line 2217, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-9807' coro=<Client._gather.<locals>.wait() done, defined at /home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py:2208> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py\", line 2217, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-9808' coro=<Client._gather.<locals>.wait() done, defined at /home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py:2208> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py\", line 2217, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-9796' coro=<Client._gather.<locals>.wait() done, defined at /home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py:2208> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py\", line 2217, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-9798' coro=<Client._gather.<locals>.wait() done, defined at /home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py:2208> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py\", line 2217, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-9799' coro=<Client._gather.<locals>.wait() done, defined at /home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py:2208> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py\", line 2217, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-9801' coro=<Client._gather.<locals>.wait() done, defined at /home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py:2208> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py\", line 2217, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-9804' coro=<Client._gather.<locals>.wait() done, defined at /home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py:2208> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py\", line 2217, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-9873' coro=<Client._gather.<locals>.wait() done, defined at /home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py:2208> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py\", line 2217, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-9889' coro=<Client._gather.<locals>.wait() done, defined at /home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py:2208> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py\", line 2217, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-9785' coro=<Client._gather.<locals>.wait() done, defined at /home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py:2208> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py\", line 2217, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-9787' coro=<Client._gather.<locals>.wait() done, defined at /home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py:2208> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py\", line 2217, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-9777' coro=<Client._gather.<locals>.wait() done, defined at /home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py:2208> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py\", line 2217, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-9778' coro=<Client._gather.<locals>.wait() done, defined at /home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py:2208> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py\", line 2217, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-9780' coro=<Client._gather.<locals>.wait() done, defined at /home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py:2208> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py\", line 2217, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-9746' coro=<Client._gather.<locals>.wait() done, defined at /home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py:2208> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py\", line 2217, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-9861' coro=<Client._gather.<locals>.wait() done, defined at /home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py:2208> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py\", line 2217, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-9899' coro=<Client._gather.<locals>.wait() done, defined at /home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py:2208> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py\", line 2217, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-9901' coro=<Client._gather.<locals>.wait() done, defined at /home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py:2208> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py\", line 2217, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-9903' coro=<Client._gather.<locals>.wait() done, defined at /home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py:2208> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py\", line 2217, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-9770' coro=<Client._gather.<locals>.wait() done, defined at /home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py:2208> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py\", line 2217, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-9893' coro=<Client._gather.<locals>.wait() done, defined at /home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py:2208> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py\", line 2217, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-9839' coro=<Client._gather.<locals>.wait() done, defined at /home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py:2208> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py\", line 2217, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-9860' coro=<Client._gather.<locals>.wait() done, defined at /home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py:2208> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py\", line 2217, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-9864' coro=<Client._gather.<locals>.wait() done, defined at /home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py:2208> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py\", line 2217, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-9867' coro=<Client._gather.<locals>.wait() done, defined at /home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py:2208> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py\", line 2217, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-9863' coro=<Client._gather.<locals>.wait() done, defined at /home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py:2208> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py\", line 2217, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-9865' coro=<Client._gather.<locals>.wait() done, defined at /home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py:2208> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py\", line 2217, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-9877' coro=<Client._gather.<locals>.wait() done, defined at /home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py:2208> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py\", line 2217, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-9874' coro=<Client._gather.<locals>.wait() done, defined at /home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py:2208> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py\", line 2217, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-9859' coro=<Client._gather.<locals>.wait() done, defined at /home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py:2208> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py\", line 2217, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-9757' coro=<Client._gather.<locals>.wait() done, defined at /home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py:2208> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py\", line 2217, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-9837' coro=<Client._gather.<locals>.wait() done, defined at /home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py:2208> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py\", line 2217, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-9788' coro=<Client._gather.<locals>.wait() done, defined at /home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py:2208> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py\", line 2217, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-9781' coro=<Client._gather.<locals>.wait() done, defined at /home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py:2208> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py\", line 2217, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-9687' coro=<Client._gather.<locals>.wait() done, defined at /home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py:2208> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py\", line 2217, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-9644' coro=<Client._gather.<locals>.wait() done, defined at /home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py:2208> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py\", line 2217, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-9672' coro=<Client._gather.<locals>.wait() done, defined at /home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py:2208> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py\", line 2217, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-9688' coro=<Client._gather.<locals>.wait() done, defined at /home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py:2208> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py\", line 2217, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-9702' coro=<Client._gather.<locals>.wait() done, defined at /home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py:2208> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py\", line 2217, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-9699' coro=<Client._gather.<locals>.wait() done, defined at /home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py:2208> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py\", line 2217, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-9592' coro=<Client._gather.<locals>.wait() done, defined at /home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py:2208> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py\", line 2217, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-9593' coro=<Client._gather.<locals>.wait() done, defined at /home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py:2208> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py\", line 2217, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-9690' coro=<Client._gather.<locals>.wait() done, defined at /home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py:2208> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py\", line 2217, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-9691' coro=<Client._gather.<locals>.wait() done, defined at /home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py:2208> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py\", line 2217, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-9692' coro=<Client._gather.<locals>.wait() done, defined at /home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py:2208> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py\", line 2217, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-9693' coro=<Client._gather.<locals>.wait() done, defined at /home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py:2208> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py\", line 2217, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-9737' coro=<Client._gather.<locals>.wait() done, defined at /home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py:2208> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py\", line 2217, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-9681' coro=<Client._gather.<locals>.wait() done, defined at /home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py:2208> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py\", line 2217, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-9682' coro=<Client._gather.<locals>.wait() done, defined at /home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py:2208> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py\", line 2217, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-9588' coro=<Client._gather.<locals>.wait() done, defined at /home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py:2208> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py\", line 2217, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-9589' coro=<Client._gather.<locals>.wait() done, defined at /home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py:2208> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py\", line 2217, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-9674' coro=<Client._gather.<locals>.wait() done, defined at /home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py:2208> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py\", line 2217, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-9675' coro=<Client._gather.<locals>.wait() done, defined at /home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py:2208> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py\", line 2217, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-9677' coro=<Client._gather.<locals>.wait() done, defined at /home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py:2208> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py\", line 2217, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-9679' coro=<Client._gather.<locals>.wait() done, defined at /home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py:2208> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py\", line 2217, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-9730' coro=<Client._gather.<locals>.wait() done, defined at /home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py:2208> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py\", line 2217, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-9664' coro=<Client._gather.<locals>.wait() done, defined at /home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py:2208> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py\", line 2217, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-9666' coro=<Client._gather.<locals>.wait() done, defined at /home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py:2208> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py\", line 2217, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-9667' coro=<Client._gather.<locals>.wait() done, defined at /home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py:2208> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py\", line 2217, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-9668' coro=<Client._gather.<locals>.wait() done, defined at /home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py:2208> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py\", line 2217, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-9581' coro=<Client._gather.<locals>.wait() done, defined at /home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py:2208> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py\", line 2217, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-9579' coro=<Client._gather.<locals>.wait() done, defined at /home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py:2208> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py\", line 2217, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-9585' coro=<Client._gather.<locals>.wait() done, defined at /home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py:2208> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py\", line 2217, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-9659' coro=<Client._gather.<locals>.wait() done, defined at /home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py:2208> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py\", line 2217, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-9660' coro=<Client._gather.<locals>.wait() done, defined at /home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py:2208> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py\", line 2217, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-9729' coro=<Client._gather.<locals>.wait() done, defined at /home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py:2208> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py\", line 2217, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-9724' coro=<Client._gather.<locals>.wait() done, defined at /home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py:2208> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py\", line 2217, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-9652' coro=<Client._gather.<locals>.wait() done, defined at /home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py:2208> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py\", line 2217, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-9655' coro=<Client._gather.<locals>.wait() done, defined at /home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py:2208> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py\", line 2217, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-9656' coro=<Client._gather.<locals>.wait() done, defined at /home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py:2208> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py\", line 2217, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-9648' coro=<Client._gather.<locals>.wait() done, defined at /home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py:2208> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py\", line 2217, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-9649' coro=<Client._gather.<locals>.wait() done, defined at /home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py:2208> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py\", line 2217, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-9650' coro=<Client._gather.<locals>.wait() done, defined at /home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py:2208> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py\", line 2217, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-9711' coro=<Client._gather.<locals>.wait() done, defined at /home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py:2208> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py\", line 2217, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-9713' coro=<Client._gather.<locals>.wait() done, defined at /home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py:2208> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py\", line 2217, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-9628' coro=<Client._gather.<locals>.wait() done, defined at /home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py:2208> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py\", line 2217, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-9629' coro=<Client._gather.<locals>.wait() done, defined at /home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py:2208> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py\", line 2217, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-9638' coro=<Client._gather.<locals>.wait() done, defined at /home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py:2208> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py\", line 2217, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-9609' coro=<Client._gather.<locals>.wait() done, defined at /home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py:2208> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py\", line 2217, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-9612' coro=<Client._gather.<locals>.wait() done, defined at /home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py:2208> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py\", line 2217, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-9615' coro=<Client._gather.<locals>.wait() done, defined at /home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py:2208> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py\", line 2217, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-9617' coro=<Client._gather.<locals>.wait() done, defined at /home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py:2208> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py\", line 2217, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-9622' coro=<Client._gather.<locals>.wait() done, defined at /home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py:2208> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py\", line 2217, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-9586' coro=<Client._gather.<locals>.wait() done, defined at /home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py:2208> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py\", line 2217, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-9595' coro=<Client._gather.<locals>.wait() done, defined at /home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py:2208> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py\", line 2217, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-9671' coro=<Client._gather.<locals>.wait() done, defined at /home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py:2208> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py\", line 2217, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-9634' coro=<Client._gather.<locals>.wait() done, defined at /home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py:2208> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py\", line 2217, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-9723' coro=<Client._gather.<locals>.wait() done, defined at /home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py:2208> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py\", line 2217, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-9657' coro=<Client._gather.<locals>.wait() done, defined at /home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py:2208> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py\", line 2217, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-9643' coro=<Client._gather.<locals>.wait() done, defined at /home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py:2208> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py\", line 2217, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-9710' coro=<Client._gather.<locals>.wait() done, defined at /home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py:2208> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py\", line 2217, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-9714' coro=<Client._gather.<locals>.wait() done, defined at /home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py:2208> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py\", line 2217, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-9721' coro=<Client._gather.<locals>.wait() done, defined at /home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py:2208> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py\", line 2217, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-9719' coro=<Client._gather.<locals>.wait() done, defined at /home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py:2208> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py\", line 2217, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-9712' coro=<Client._gather.<locals>.wait() done, defined at /home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py:2208> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py\", line 2217, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-9715' coro=<Client._gather.<locals>.wait() done, defined at /home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py:2208> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py\", line 2217, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-9727' coro=<Client._gather.<locals>.wait() done, defined at /home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py:2208> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py\", line 2217, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-9725' coro=<Client._gather.<locals>.wait() done, defined at /home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py:2208> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py\", line 2217, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-9706' coro=<Client._gather.<locals>.wait() done, defined at /home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py:2208> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py\", line 2217, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-9707' coro=<Client._gather.<locals>.wait() done, defined at /home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py:2208> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py\", line 2217, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-9708' coro=<Client._gather.<locals>.wait() done, defined at /home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py:2208> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py\", line 2217, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-9709' coro=<Client._gather.<locals>.wait() done, defined at /home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py:2208> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py\", line 2217, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-9577' coro=<Client._gather.<locals>.wait() done, defined at /home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py:2208> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py\", line 2217, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-9575' coro=<Client._gather.<locals>.wait() done, defined at /home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py:2208> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py\", line 2217, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-9582' coro=<Client._gather.<locals>.wait() done, defined at /home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py:2208> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py\", line 2217, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-9580' coro=<Client._gather.<locals>.wait() done, defined at /home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py:2208> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py\", line 2217, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-9670' coro=<Client._gather.<locals>.wait() done, defined at /home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py:2208> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py\", line 2217, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-9701' coro=<Client._gather.<locals>.wait() done, defined at /home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py:2208> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py\", line 2217, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-9738' coro=<Client._gather.<locals>.wait() done, defined at /home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py:2208> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py\", line 2217, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-9584' coro=<Client._gather.<locals>.wait() done, defined at /home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py:2208> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py\", line 2217, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-9636' coro=<Client._gather.<locals>.wait() done, defined at /home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py:2208> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py\", line 2217, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-9637' coro=<Client._gather.<locals>.wait() done, defined at /home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py:2208> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py\", line 2217, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-9639' coro=<Client._gather.<locals>.wait() done, defined at /home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py:2208> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py\", line 2217, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-9642' coro=<Client._gather.<locals>.wait() done, defined at /home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py:2208> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py\", line 2217, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-9624' coro=<Client._gather.<locals>.wait() done, defined at /home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py:2208> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py\", line 2217, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-9625' coro=<Client._gather.<locals>.wait() done, defined at /home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py:2208> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py\", line 2217, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-9630' coro=<Client._gather.<locals>.wait() done, defined at /home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py:2208> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py\", line 2217, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-9632' coro=<Client._gather.<locals>.wait() done, defined at /home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py:2208> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py\", line 2217, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-9616' coro=<Client._gather.<locals>.wait() done, defined at /home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py:2208> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py\", line 2217, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-9618' coro=<Client._gather.<locals>.wait() done, defined at /home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py:2208> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py\", line 2217, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-9620' coro=<Client._gather.<locals>.wait() done, defined at /home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py:2208> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py\", line 2217, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-9621' coro=<Client._gather.<locals>.wait() done, defined at /home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py:2208> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py\", line 2217, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-9605' coro=<Client._gather.<locals>.wait() done, defined at /home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py:2208> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py\", line 2217, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-9606' coro=<Client._gather.<locals>.wait() done, defined at /home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py:2208> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py\", line 2217, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-9608' coro=<Client._gather.<locals>.wait() done, defined at /home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py:2208> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py\", line 2217, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-9610' coro=<Client._gather.<locals>.wait() done, defined at /home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py:2208> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py\", line 2217, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-9613' coro=<Client._gather.<locals>.wait() done, defined at /home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py:2208> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py\", line 2217, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-9601' coro=<Client._gather.<locals>.wait() done, defined at /home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py:2208> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py\", line 2217, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-9603' coro=<Client._gather.<locals>.wait() done, defined at /home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py:2208> exception=AllExit()>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/client.py\", line 2217, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n"
     ]
    }
   ],
   "source": [
    "from dask.distributed import Client\n",
    "\n",
    "client = Client(n_workers=8, threads_per_worker=1, memory_limit=\"2GiB\")"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "a4a63c90-c121-4f4b-b7d2-38e44c12ec5f",
   "metadata": {},
   "source": [
    "### Red camera"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "f63a1c6c-5716-40ee-90c0-8e24eb4a1816",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Locating and converting where necessary: 100%|██████████| 60/60 [00:00<00:00, 1783.41it/s]\n",
      "Reading netCDF files... took 6.88 s. Size is 27397.908 Mb\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2024-02-28 19:22:39,476 - distributed.worker.state_machine - WARNING - Async instruction for <Task cancelled name=\"execute(('concatenate-open_dataset-getitem-b2f00c785c2ff18829eeaace2f95846c', 10, 0, 0))\" coro=<Worker.execute() done, defined at /home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/worker_state_machine.py:3615>> ended with CancelledError\n",
      "2024-02-28 19:22:39,483 - distributed.worker.state_machine - WARNING - Async instruction for <Task cancelled name=\"execute(('concatenate-where-getitem-3cd475536cc7f23557465c85048c4cff', 23, 0, 0))\" coro=<Worker.execute() done, defined at /home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/worker_state_machine.py:3615>> ended with CancelledError\n",
      "2024-02-28 19:22:39,483 - distributed.worker.state_machine - WARNING - Async instruction for <Task cancelled name=\"execute(('where-getitem-9f75473910392f2ba3ace49952448c93', 8, 0, 0))\" coro=<Worker.execute() done, defined at /home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/worker_state_machine.py:3615>> ended with CancelledError\n",
      "2024-02-28 19:22:39,484 - distributed.worker.state_machine - WARNING - Async instruction for <Task cancelled name=\"execute(('concatenate-where-getitem-3cd475536cc7f23557465c85048c4cff', 1, 0, 0))\" coro=<Worker.execute() done, defined at /home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/worker_state_machine.py:3615>> ended with CancelledError\n",
      "2024-02-28 19:22:39,485 - distributed.worker.state_machine - WARNING - Async instruction for <Task cancelled name=\"execute(('concatenate-open_dataset-getitem-3cd475536cc7f23557465c85048c4cff', 3, 0, 0))\" coro=<Worker.execute() done, defined at /home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/worker_state_machine.py:3615>> ended with CancelledError\n",
      "2024-02-28 19:22:39,491 - distributed.worker.state_machine - WARNING - Async instruction for <Task cancelled name=\"execute(('open_dataset-getitem-1438da9a2029d19aa369818d191b34ba', 0, 0, 0))\" coro=<Worker.execute() done, defined at /home2/bamford/anaconda/envs/qagmire/lib/python3.12/site-packages/distributed/worker_state_machine.py:3615>> ended with CancelledError\n"
     ]
    },
    {
     "ename": "KeyboardInterrupt",
     "evalue": "",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mKeyboardInterrupt\u001b[0m                         Traceback (most recent call last)",
      "Cell \u001b[0;32mIn[5], line 2\u001b[0m\n\u001b[1;32m      1\u001b[0m tests \u001b[38;5;241m=\u001b[39m L1SpectrumValueCheck(camera\u001b[38;5;241m=\u001b[39m\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mRED\u001b[39m\u001b[38;5;124m\"\u001b[39m)\n\u001b[0;32m----> 2\u001b[0m \u001b[43mtests\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mrun\u001b[49m\u001b[43m(\u001b[49m\u001b[43mdate\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[38;5;124;43m\"\u001b[39;49m\u001b[38;5;124;43m2017*\u001b[39;49m\u001b[38;5;124;43m\"\u001b[39;49m\u001b[43m)\u001b[49m\n",
      "File \u001b[0;32m~/qagmire/qagmire/quality_assurance.py:58\u001b[0m, in \u001b[0;36mDiagnostics.run\u001b[0;34m(self, **kwargs)\u001b[0m\n\u001b[1;32m     56\u001b[0m detail\u001b[38;5;241m.\u001b[39mname \u001b[38;5;241m=\u001b[39m \u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mfailed\u001b[39m\u001b[38;5;124m\"\u001b[39m\n\u001b[1;32m     57\u001b[0m start \u001b[38;5;241m=\u001b[39m time\u001b[38;5;241m.\u001b[39mperf_counter()\n\u001b[0;32m---> 58\u001b[0m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mdetail \u001b[38;5;241m=\u001b[39m \u001b[43mdask\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mcompute\u001b[49m\u001b[43m(\u001b[49m\u001b[43mdetail\u001b[49m\u001b[43m)\u001b[49m[\u001b[38;5;241m0\u001b[39m]\n\u001b[1;32m     59\u001b[0m detail\u001b[38;5;241m.\u001b[39mclose()\n\u001b[1;32m     61\u001b[0m dt \u001b[38;5;241m=\u001b[39m time\u001b[38;5;241m.\u001b[39mperf_counter() \u001b[38;5;241m-\u001b[39m start\n",
      "File \u001b[0;32m~/anaconda/envs/qagmire/lib/python3.12/site-packages/dask/base.py:665\u001b[0m, in \u001b[0;36mcompute\u001b[0;34m(traverse, optimize_graph, scheduler, get, *args, **kwargs)\u001b[0m\n\u001b[1;32m    662\u001b[0m     postcomputes\u001b[38;5;241m.\u001b[39mappend(x\u001b[38;5;241m.\u001b[39m__dask_postcompute__())\n\u001b[1;32m    664\u001b[0m \u001b[38;5;28;01mwith\u001b[39;00m shorten_traceback():\n\u001b[0;32m--> 665\u001b[0m     results \u001b[38;5;241m=\u001b[39m \u001b[43mschedule\u001b[49m\u001b[43m(\u001b[49m\u001b[43mdsk\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mkeys\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[38;5;241;43m*\u001b[39;49m\u001b[38;5;241;43m*\u001b[39;49m\u001b[43mkwargs\u001b[49m\u001b[43m)\u001b[49m\n\u001b[1;32m    667\u001b[0m \u001b[38;5;28;01mreturn\u001b[39;00m repack([f(r, \u001b[38;5;241m*\u001b[39ma) \u001b[38;5;28;01mfor\u001b[39;00m r, (f, a) \u001b[38;5;129;01min\u001b[39;00m \u001b[38;5;28mzip\u001b[39m(results, postcomputes)])\n",
      "File \u001b[0;32m~/anaconda/envs/qagmire/lib/python3.12/threading.py:655\u001b[0m, in \u001b[0;36mEvent.wait\u001b[0;34m(self, timeout)\u001b[0m\n\u001b[1;32m    653\u001b[0m signaled \u001b[38;5;241m=\u001b[39m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_flag\n\u001b[1;32m    654\u001b[0m \u001b[38;5;28;01mif\u001b[39;00m \u001b[38;5;129;01mnot\u001b[39;00m signaled:\n\u001b[0;32m--> 655\u001b[0m     signaled \u001b[38;5;241m=\u001b[39m \u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43m_cond\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mwait\u001b[49m\u001b[43m(\u001b[49m\u001b[43mtimeout\u001b[49m\u001b[43m)\u001b[49m\n\u001b[1;32m    656\u001b[0m \u001b[38;5;28;01mreturn\u001b[39;00m signaled\n",
      "File \u001b[0;32m~/anaconda/envs/qagmire/lib/python3.12/threading.py:359\u001b[0m, in \u001b[0;36mCondition.wait\u001b[0;34m(self, timeout)\u001b[0m\n\u001b[1;32m    357\u001b[0m \u001b[38;5;28;01melse\u001b[39;00m:\n\u001b[1;32m    358\u001b[0m     \u001b[38;5;28;01mif\u001b[39;00m timeout \u001b[38;5;241m>\u001b[39m \u001b[38;5;241m0\u001b[39m:\n\u001b[0;32m--> 359\u001b[0m         gotit \u001b[38;5;241m=\u001b[39m \u001b[43mwaiter\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43macquire\u001b[49m\u001b[43m(\u001b[49m\u001b[38;5;28;43;01mTrue\u001b[39;49;00m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mtimeout\u001b[49m\u001b[43m)\u001b[49m\n\u001b[1;32m    360\u001b[0m     \u001b[38;5;28;01melse\u001b[39;00m:\n\u001b[1;32m    361\u001b[0m         gotit \u001b[38;5;241m=\u001b[39m waiter\u001b[38;5;241m.\u001b[39macquire(\u001b[38;5;28;01mFalse\u001b[39;00m)\n",
      "\u001b[0;31mKeyboardInterrupt\u001b[0m: "
     ]
    }
   ],
   "source": [
    "tests = L1SpectrumValueCheck(camera=\"RED\")\n",
    "tests.run(date=\"2017*\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "c30d0f7d-2bb6-4bd6-9b2b-52e0c1d16bfd",
   "metadata": {},
   "outputs": [],
   "source": [
    "tests.summary(by=\"RUN\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "0fddfe97-0cdf-4095-a97d-d8e93d636836",
   "metadata": {},
   "outputs": [],
   "source": [
    "tests.summary(by=\"NSPEC\")"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "d519845a-906b-4c7d-938d-5d9e48f82587",
   "metadata": {},
   "source": [
    "### Blue camera"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "69d6e0d1-0ec6-4fd5-b351-23ffdfc48ee7",
   "metadata": {},
   "outputs": [],
   "source": [
    "tests = L1SpectrumValueCheck(camera=\"BLUE\")\n",
    "tests.run(date=\"2017*\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "c66b1cb0-427c-4b85-a944-4e4b441c3ae2",
   "metadata": {},
   "outputs": [],
   "source": [
    "tests.summary(by=\"RUN\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "2e3f8f24-7f64-4f3b-b50b-7bf20ddc2638",
   "metadata": {},
   "outputs": [],
   "source": [
    "tests.summary(by=\"NSPEC\")"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "77b16a23-68d1-4ea7-8c08-e66b0641e09c",
   "metadata": {},
   "source": [
    "## Verification"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "d2754ef2-5a4a-4dc4-a9cd-fb01d2effc64",
   "metadata": {},
   "outputs": [],
   "source": [
    "files = get_lr_l1_single_files(date=\"2017*\")\n",
    "data = read_l1_data(files)\n",
    "data = data.swap_dims(filename=\"RUN\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "14284756-a188-4635-b7a6-46923d0ece14",
   "metadata": {},
   "outputs": [],
   "source": [
    "def plot(run, ext):\n",
    "    qty = data.sel(RUN=run)[ext]\n",
    "    fig, ax = plt.subplots(3, 1, figsize=(15, 5), sharex=True, sharey=True)\n",
    "    ax[0].imshow(qty, vmin=0, vmax=100, interpolation=\"none\")\n",
    "    ax[0].set_title(ext)\n",
    "    ax[1].imshow(~np.isfinite(qty), interpolation=\"none\")\n",
    "    ax[1].set_title(\"NaNs\")\n",
    "    ax[2].imshow(qty < 0, interpolation=\"none\")\n",
    "    ax[2].set_title(\"Negs\")\n",
    "    fig.suptitle(f\"RUN {run}\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "d9db5899-18fa-40ca-812d-61b8f9b07f01",
   "metadata": {},
   "outputs": [],
   "source": [
    "plot(1004097, \"RED_FLUX\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "23886b9f-3436-4932-97e8-57e19ab8cd8d",
   "metadata": {},
   "outputs": [],
   "source": [
    "plot(1004098, \"BLUE_FLUX\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "51fc7796-aa4b-46aa-a260-9418ae2c6537",
   "metadata": {},
   "outputs": [],
   "source": [
    "plot(1003329, \"RED_FLUX\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "bac1ae25-361c-48ab-9cab-2b1b10cdcc1d",
   "metadata": {},
   "outputs": [],
   "source": [
    "plot(1003330, \"BLUE_FLUX\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "fca8bb45-e1aa-4315-9aa1-14e36190cfa6",
   "metadata": {},
   "outputs": [],
   "source": [
    "# |hide\n",
    "import nbdev\n",
    "\n",
    "nbdev.nbdev_export()"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "python3",
   "language": "python",
   "name": "python3"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
